version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: alberdb
      POSTGRES_PASSWORD: holamundodb
      POSTGRES_DB: dblogin
    ports:
      - "5432:5432"
